#!/bin/bash

set -e

# get the field after password
# gpg2 -q -d "$HOME/.authinfo.gpg" | grep "$1" | sed -r 's/^.?+password "(.+)"$/\1/'

# password
gpg2 -q -d "$HOME/.authinfo.gpg" | grep "$1" | awk -F'"' '{ print $2 }'
